// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl7gDLf-pZRrdK6lBJWKBFQ9vVyR4DPX8',
    appId: '1:842953545763:web:134645cc41d72337c57996',
    messagingSenderId: '842953545763',
    projectId: 'bingoirl-e6917',
    authDomain: 'bingoirl-e6917.firebaseapp.com',
    storageBucket: 'bingoirl-e6917.firebasestorage.app',
    measurementId: 'G-TKGYZMEY6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCY3sjQDJ6lOj2sRtMu57FkqbZiyWNqp4',
    appId: '1:842953545763:android:5fc7e9f0263d86a5c57996',
    messagingSenderId: '842953545763',
    projectId: 'bingoirl-e6917',
    storageBucket: 'bingoirl-e6917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU0IGinn8Ut8AQtk2GLzVnrD6tpjCtpl4',
    appId: '1:842953545763:ios:67ea65f178709338c57996',
    messagingSenderId: '842953545763',
    projectId: 'bingoirl-e6917',
    storageBucket: 'bingoirl-e6917.firebasestorage.app',
    iosBundleId: 'com.example.bingoHostApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU0IGinn8Ut8AQtk2GLzVnrD6tpjCtpl4',
    appId: '1:842953545763:ios:67ea65f178709338c57996',
    messagingSenderId: '842953545763',
    projectId: 'bingoirl-e6917',
    storageBucket: 'bingoirl-e6917.firebasestorage.app',
    iosBundleId: 'com.example.bingoHostApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl7gDLf-pZRrdK6lBJWKBFQ9vVyR4DPX8',
    appId: '1:842953545763:web:5ef539988fa18471c57996',
    messagingSenderId: '842953545763',
    projectId: 'bingoirl-e6917',
    authDomain: 'bingoirl-e6917.firebaseapp.com',
    storageBucket: 'bingoirl-e6917.firebasestorage.app',
    measurementId: 'G-578DCZNT6K',
  );
}
